// Authoring record. Do not replay over designer changes. SOURCE injected from source.json.
if(figma.root.children.some(p=>p.name==='02 · UX refinement'))throw Error('UX page exists; update known nodes instead');
await Promise.all(['Regular','Medium','Bold'].map(style=>figma.loadFontAsync({family:'Noto Sans JP',style})));
const buttons={};for(const [kind,id] of Object.entries({primary:'5:266',secondary:'5:269',accent:'5:272'})){const c=await figma.getNodeByIdAsync(id);buttons[kind]={c,key:Object.keys(c.componentPropertyDefinitions)[0]};}
const vars=await figma.variables.getLocalVariablesAsync();const tokens=Object.fromEntries(vars.filter(v=>v.variableCollectionId==='VariableCollectionId:5:167').map(v=>[v.name,v]));
const styles=await figma.getLocalTextStylesAsync();const ts=Object.fromEntries(styles.map(s=>[s.name.split('/').pop(),s]));
const page=figma.createPage();page.name='02 · UX refinement';await figma.setCurrentPageAsync(page);
const colors={ink:'#182a24',muted:'#6f7a74',line:'#e2e7e3',green:'#173e30',lime:'#d6f887',surface:'#f6f8f5',white:'#ffffff',sidebar:'#142c23',subtle:'#f0f5e9',feature:'#1d402f',onDark:'#e5ece6',darkMuted:'#b3c4b9',input:'#fcfdfb'};
const rgb=h=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
function paint(k){const p={type:'SOLID',color:rgb(colors[k]||k)};return tokens['color/'+k]?figma.variables.setBoundVariableForPaint(p,'color',tokens['color/'+k]):p;}
function bind(n,k,v,group='spacing'){n[k]=v;if(tokens[group+'/'+v])n.setBoundVariable(k,tokens[group+'/'+v]);}
function box(p,name,w,dir='VERTICAL',bg=null,gap=0,pad=0){const n=figma.createAutoLayout(dir);n.name=name;p.appendChild(n);n.resize(w,1);n.primaryAxisSizingMode=dir==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=dir==='VERTICAL'?'FIXED':'AUTO';n.fills=bg?[paint(bg)]:[];bind(n,'itemSpacing',gap);for(const k of ['paddingTop','paddingRight','paddingBottom','paddingLeft'])bind(n,k,pad);return n;}
function txt(p,s,style='Small',color='ink',w){const n=figma.createText();n.fontName={family:'Noto Sans JP',style:'Regular'};n.characters=s;n.name=s.slice(0,42);n.textStyleId=ts[style].id;n.fills=[paint(color)];p.appendChild(n);if(w){n.textAutoResize='HEIGHT';n.resize(w,n.height);}return n;}
function round(n,r=8){n.cornerRadius=r;for(const k of ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius'])if(tokens['radius/'+r])n.setBoundVariable(k,tokens['radius/'+r]);return n;}
function stroke(n){n.strokes=[paint('line')];n.strokeWeight=1;return n;}
function row(p,name,w,gap=12,bg=null,pad=0){const n=box(p,name,w,'HORIZONTAL',bg,gap,pad);n.counterAxisAlignItems='CENTER';return n;}
function between(n){n.primaryAxisAlignItems='SPACE_BETWEEN';return n;}
function fixed(n,w,h){n.resize(w,h);n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';return n;}
function icon(p,name,size=20,color='ink'){const n=figma.createNodeFromSvg(SOURCE.icons[name].replaceAll('currentColor',colors[color]));p.appendChild(n);n.name='Icon/'+name;n.resize(size,size);return n;}
function btn(p,label,kind='secondary'){const a=buttons[kind],n=a.c.createInstance();p.appendChild(n);n.setProperties({[a.key]:label});return n;}
function chip(p,s,active=false){const n=round(row(p,'Status / '+s,100,0,active?'subtle':'surface',6),5);n.primaryAxisSizingMode='AUTO';txt(n,s,'Caption',active?'green':'ink');return n;}
const links=[],screens={},components={};
function nav(n,d){links.push([n,d]);return n;}
const shelf=box(page,'UX v2 / Components',1440,'VERTICAL','white',24,32);shelf.x=80;shelf.y=2500;txt(shelf,'UX v2 / Components','Title');
const side=box(shelf,'Sidebar',208,'VERTICAL','sidebar',28,20);fixed(side,208,900);
const logo=row(side,'Brand',168,8);icon(logo,'FlaskConical',21,'lime');txt(logo,'concentrate','Card title','white');
const workspace=round(stroke(row(side,'Workspace switcher',168,10,null,10)));txt(workspace,'将','Card title','lime');txt(workspace,'ShogunAI ⌄','Label','white');
const sidebarNav=box(side,'Navigation',168,'VERTICAL',null,8);const selected=round(row(sidebarNav,'Projects',168,10,'lime',12));icon(selected,'LayoutGrid',18);txt(selected,'企画','Label');
const brandNav=round(row(sidebarNav,'Brand settings',168,10,null,12));icon(brandNav,'BookOpen',18,'darkMuted');txt(brandNav,'ブランド','Label','darkMuted');
const space=box(side,'Flexible space',168);space.layoutSizingVertical='FILL';
const help=row(side,'Help',168,10);txt(help,'?','Label','darkMuted');txt(help,'使い方','Small','darkMuted');
const profile=row(side,'Account',168,10);chip(profile,'T');txt(profile,'Toru','Label','white');
const sideComp=figma.createComponentFromNode(side);sideComp.name='UX v2/Sidebar';sideComp.description='企画がグローバルの入口。原液と媒体別は企画内タブ。ブランド設定は別画面。';components.sidebar=sideComp.id;
function shell(key,name,x,y){const root=box(page,name,1440,'HORIZONTAL','surface');root.x=x;root.y=y;fixed(root,1440,960);root.clipsContent=true;screens[key]=root;
const si=sideComp.createInstance();root.appendChild(si);si.resize(208,960);nav(si.findOne(n=>n.name==='Projects'),'library');
const main=box(root,'Main',1232,'VERTICAL','white');const top=between(row(main,'Workspace bar',1232,16,'white',20));fixed(top,1232,64);txt(top,'ShogunAI  /  企画','Small');const right=row(top,'Utilities',210,16);txt(right,'⌕  検索','Small','ink');txt(right,'⌘ K','Caption','muted');btn(right,'読み込む');return {root,main};}
function heading(main,title,action){const h=between(row(main,'Page heading',1232,24,null,32));const t=txt(h,title,'Title');if(action)return {h,action:btn(h,action,'primary')};return {h};}
function titleBar(main,key){const h=between(row(main,'Project title bar',1232,16,null,24));const c=box(h,'Project identity',800,'VERTICAL',null,4);nav(txt(c,'← 企画','Small','green'),'library');txt(c,'月曜の朝、金曜の自分に聞けたら。','Heading');const a=box(h,'Save state',270,'VERTICAL',null,8);txt(a,'✓ 保存済み   ·   たった今','Caption','ink');nav(btn(a,key==='editor'?'媒体別ドラフトへ':'制作データを書き出す','primary'),key==='editor'?'outputs':'handoff');const tabs=row(main,'Project tabs',1232,28,'white',24);nav(txt(tabs,'原液','Label',key==='editor'?'green':'muted'),'editor');nav(txt(tabs,'媒体別  2','Label',key==='outputs'?'green':'muted'),'outputs');txt(tabs,'履歴','Label','muted');stroke(tabs);}
const lib=shell('library','01 / 企画',80,80);const lh=heading(lib.main,'企画','＋ 新しい企画');nav(lh.action,'create');
const lb=box(lib.main,'Project list',1232,'VERTICAL',null,24,32);
const resume=round(stroke(between(row(lb,'Resume',1168,24,'surface',20))));const rr=box(resume,'Resume identity',740,'VERTICAL',null,6);txt(rr,'編集中','Caption','green');txt(rr,'月曜の朝、金曜の自分に聞けたら。','Card title');nav(btn(resume,'編集を続ける →','primary'),'editor');
const filters=between(row(lb,'Filters',1168,20));const ft=row(filters,'Status tabs',690,24);for(const [i,s] of ['すべて 5','原液を編集中 2','媒体を編集中 2','制作待ち 1'].entries())txt(ft,s,'Label',i===0?'green':'muted');btn(filters,'企画軸  ⌄');
const table=box(lb,'Ideas table',1168,'VERTICAL','white');const th=row(table,'Table header',1168,20,'surface',16);for(const [s,w] of [['企画',520],['ステータス',154],['媒体',138],['更新',90]])txt(th,s,'Caption','ink',w);
const data=[['月曜の朝、金曜の自分に聞けたら。','ユースケース · 創業者','原液を編集中','X · ショート','今'],['AIに背景説明、今日何回した？','機能便益 · フリーランス','媒体を編集中','X · 記事','12分前'],['会議5分前、前回の「なぜ」を取り戻す。','ペルソナ · PM','制作待ち','ショート','1時間前'],['昨日の決定を覚えている家臣。','マスコット','原液を編集中','—','昨日'],['積み上がるのは、タスクではなく自分の城。','城の世界観','媒体を編集中','X · 記事','昨日']];
for(const [i,d] of data.entries()){const r=stroke(row(table,'Idea / '+i,1168,20,i===0?'input':'white',16));const c=box(r,'Identity',520,'VERTICAL',null,5);txt(c,d[0],'Label');txt(c,d[1],'Caption','muted');const st=box(r,'Stage',154);chip(st,d[2],i===0);txt(r,d[3],'Small','ink',138);txt(r,d[4],'Caption','muted',90);nav(txt(r,'→','Body'),'editor');nav(r,'editor');}
txt(lb,'5 件','Caption','muted');
const ed=shell('editor','03 / 原液を編集',1600,80);titleBar(ed.main,'editor');const eb=row(ed.main,'Editor workspace',1232,24,'surface',24);eb.counterAxisAlignItems='MIN';
const doc=round(stroke(box(eb,'Document canvas',816,'VERTICAL','white',24,32)));const toolbar=between(row(doc,'Editor toolbar',752,12));txt(toolbar,'本文  ⌄    B    I    ≡    ↗','Small');nav(btn(toolbar,'AIで編集'),'compare');
const brief=row(doc,'Brief tags',752,12);chip(brief,'創業者');chip(brief,'ユースケース');chip(brief,'原液 v2');
txt(doc,'月曜の朝、金曜の自分に聞けたら。','Title','ink',728);
txt(doc,'月曜の朝、最初にやる仕事が「先週の仕事を思い出すこと」になっていないだろうか。','Body','ink',728);
const sel=round(box(doc,'Selected paragraph',752,'VERTICAL','subtle',0,12),4);txt(sel,'必要なのは、全部の履歴を読み直すことではない。何を決めて、なぜそう決めて、何が残ったのか。そのつながりだ。','Body','ink',728);
txt(doc,'ShogunAIが掲げるのは、仕事の記憶を必要な文脈として呼び出し、次の作業へつなげる体験。過去の判断を根拠と一緒に確認できれば、仕事の再開はどう変わるだろう。','Body','ink',728);
txt(doc,'金曜の意思決定から、月曜の再開まで。\n実際の画面を使って、一つの仕事の続きを追ってみたい。','Body','ink',728);
const foot=between(row(doc,'Document footer',752));txt(foot,'本文  ·  284文字','Caption','muted');txt(foot,'最終編集：Toru','Caption','muted');
const ctx=box(eb,'Context rail',344,'VERTICAL',null,20);const cc=round(stroke(box(ctx,'Brief',344,'VERTICAL','white',12,20)));txt(cc,'企画メモ','Label');txt(cc,'主張','Caption','muted');txt(cc,'仕事を再開する前に、文脈を探し直す時間を減らす。','Small','ink',304);txt(cc,'構成','Caption','muted');txt(cc,'月曜の迷い → 過去の判断 → 次の一手','Small','ink',304);btn(cc,'メモを編集');
const scene=round(stroke(box(ctx,'Scenes',344,'VERTICAL','white',12,20)));txt(scene,'具体シーン','Label');txt(scene,'金曜に中断した案件を開く。\n前回の決定を確認して、作業を再開。','Small','ink',304);btn(scene,'＋ シーンを追加');
const sources=round(stroke(box(ctx,'Evidence',344,'VERTICAL','white',12,20)));between(row(sources,'Sources title',304));txt(sources,'根拠・素材  1','Label');txt(sources,'↗ ShogunAI 公式サイト','Small','green');chip(sources,'実機デモ：未確認');
const out=shell('outputs','04 / 媒体別ドラフト',3120,80);titleBar(out.main,'outputs');const ow=row(out.main,'Channel workspace',1232,24,'surface',24);ow.counterAxisAlignItems='MIN';const ch=box(ow,'Channels',210,'VERTICAL',null,12);txt(ch,'媒体','Label');for(const [s,v] of [['X','編集中'],['ショート動画','下書き'],['記事','未作成'],['Reddit','未作成'],['ロング動画','未作成']]){const r=round(box(ch,'Channel / '+s,210,'VERTICAL',s==='X'?'white':null,4,16));if(s==='X')stroke(r);txt(r,s,'Label');txt(r,v,'Caption','muted');}btn(ch,'＋ 媒体を追加');
const op=round(stroke(box(ow,'Channel editor',626,'VERTICAL','white',24,28)));const ot=between(row(op,'Channel header',570));txt(ot,'X','Heading');chip(ot,'単発投稿');
const stale=round(box(op,'Source revision notice',570,'VERTICAL','subtle',12,16));txt(stale,'原液が v2 に更新されました','Label');nav(btn(stale,'変更を確認'),'compare');
txt(op,'月曜の朝、最初の仕事が\n「先週の仕事を思い出すこと」になっていませんか。\n\n何を決めたか。なぜそう決めたか。\n残った論点は何か。\n\n仕事の続きを始めるために、\n取り戻したいのは、その文脈。','Body','ink',570);
const oa=between(row(op,'Channel actions',570));txt(oa,'原液 v1  ·  手動編集あり','Caption','ink');btn(oa,'本文をコピー');
const preview=box(ow,'Production context',300,'VERTICAL',null,20);const pc=round(stroke(box(preview,'Publish preview',300,'VERTICAL','white',16,20)));txt(pc,'プレビュー','Label');txt(pc,'ShogunAI  @ShogunAI','Label');txt(pc,'月曜の朝、最初の仕事が\n「先週の仕事を思い出すこと」になっていませんか。\n\n何を決めたか。なぜそう決めたか。残った論点は何か。','Small','ink',260);txt(pc,'♡     ↻     ↗','Small','muted');const state=round(stroke(box(preview,'Review',300,'VERTICAL','white',12,20)));txt(state,'制作ステータス','Label');chip(state,'編集中',true);nav(btn(state,'制作待ちにする','primary'),'handoff');
const create=shell('create','02 / 新しい企画',80,1140);const nh=heading(create.main,'新しい企画');const form=round(stroke(box(create.main,'New idea form',850,'VERTICAL','white',24,32)));form.layoutAlign='CENTER';txt(form,'アイデア','Label');const input=round(stroke(box(form,'Idea input',786,'VERTICAL','input',0,20)));txt(input,'月曜の朝に、先週の仕事を思い出す時間がかかる。\n創業者に向けて、仕事の文脈を取り戻すシーンを作りたい。','Body','ink',746);fixed(input,786,156);
const opts=row(form,'Optional settings',786,20);const p=box(opts,'Persona',383,'VERTICAL',null,8);txt(p,'ペルソナ','Label');const pfield=round(stroke(row(p,'Persona value',383,12,'white',12)));txt(pfield,'創業者  ⌄','Small');const axis=box(opts,'Axis',383,'VERTICAL',null,8);txt(axis,'企画軸','Label');const af=round(stroke(row(axis,'Axis value',383,12,'white',12)));txt(af,'ユースケース  ⌄','Small');
const att=between(row(form,'Attachments',786));btn(att,'＋ 参考URL・素材');txt(att,'ShogunAI のブランド設定を使用','Caption','muted');const ca=between(row(form,'Create actions',786));nav(btn(ca,'キャンセル'),'library');nav(btn(ca,'原液を作成','primary'),'editor');
const compare=shell('compare','05 / 変更を確認',1600,1140);heading(compare.main,'変更を確認');const cb=box(compare.main,'Diff workspace',1232,'VERTICAL','surface',24,32);const ctop=between(row(cb,'Diff controls',1168));txt(ctop,'X  /  原液 v1 → v2','Label');chip(ctop,'手動編集を保持',true);
const diffs=row(cb,'Before and after',1168,24);diffs.counterAxisAlignItems='MIN';const before=round(stroke(box(diffs,'Current draft',572,'VERTICAL','white',20,24)));txt(before,'現在の本文','Label');txt(before,'月曜の朝、最初の仕事が\n「先週の仕事を思い出すこと」になっていませんか。\n\n何を決めたか。なぜそう決めたか。\n残った論点は何か。\n\n仕事の続きを始めるために、\n取り戻したいのは、その文脈。','Body','ink',524);
const after=round(stroke(box(diffs,'Suggested draft',572,'VERTICAL','white',20,24)));txt(after,'変更案','Label');txt(after,'月曜の朝、最初の仕事が\n「先週の仕事を思い出すこと」になっていませんか。','Body','ink',524);const add=round(box(after,'Added text',524,'VERTICAL','subtle',8,12),4);txt(add,'＋ 金曜に止まった案件を開く。\n前回の決定を確かめて、次の一手へ。','Body','green',500);txt(after,'仕事の続きを始めるために、\n取り戻したいのは、その文脈。','Body','ink',524);
const da=between(row(cb,'Diff decisions',1168));nav(btn(da,'現在の本文を残す'),'outputs');nav(btn(da,'変更案を適用','primary'),'handoff');
const hand=shell('handoff','06 / 制作待ち',3120,1140);heading(hand.main,'制作待ち');const hb=box(hand.main,'Production package',1232,'VERTICAL',null,24,32);txt(hb,'月曜の朝、金曜の自分に聞けたら。','Heading');const ready=round(stroke(box(hb,'Ready deliverables',1168,'VERTICAL','white',20,24)));const ra=between(row(ready,'Ready header',1120));chip(ra,'制作待ち',true);nav(btn(ra,'編集に戻る'),'outputs');for(const [n,s] of [['X','本文 · 原液 v2'],['ショート動画','台本 · シーン案 · 素材リスト']]){const r=between(stroke(row(ready,n,1120,20,'input',20)));const c=box(r,'Deliverable',730,'VERTICAL',null,6);txt(c,n,'Label');txt(c,s,'Small','muted');btn(r,'書き出す');}btn(hb,'制作データをまとめて書き出す','primary');
const guide=box(page,'UX decisions / Not product UI',1440,'VERTICAL','white',20,32);guide.x=80;guide.y=-530;txt(guide,'AI Concentrate · UX refinement','Display');txt(guide,'デザイン提案 / 未実装 / 2026-10-02','Label','green');txt(guide,'企画 → 原液 → 媒体別 → 制作待ち。説明文やスローガンを常設せず、内容と操作を優先。\n保存済み・AI作成・差分適用は次段階の設計。現在の公開プロトタイプの動作とは分離しています。\nFigma上の入力・生成・ダウンロードは画面遷移のシミュレーションです。','Body','ink',1376);txt(guide,'レビュー開始：01 / 企画。新しい企画 → 原液を作成 → 媒体別ドラフトへ → 変更を確認。','Small');
for(const [n,d] of links){let top=n;while(top.parent&&top.parent!==page)top=top.parent;if(top===screens[d])continue;await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'NODE',destinationId:screens[d].id,navigation:'NAVIGATE',transition:null}]}]);}page.flowStartingPoints=[{nodeId:screens.library.id,name:'企画から制作へ'}];
const all=page.findAll(()=>true);return {pageId:page.id,screenIds:Object.fromEntries(Object.entries(screens).map(([k,n])=>[k,n.id])),components,guideId:guide.id,shelfId:shelf.id,createdNodeIds:[page.id,...all.map(n=>n.id)],links:links.map(([n,d])=>({id:n.id,target:screens[d].id})),bounds:Object.fromEntries(Object.entries(screens).map(([k,n])=>[k,{width:n.width,height:n.height}])),counts:all.reduce((o,n)=>(o[n.type]=(o[n.type]||0)+1,o),{})};
