const page=await figma.getNodeByIdAsync('20:391');await figma.setCurrentPageAsync(page);
const buttonComps={Primary:await figma.getNodeByIdAsync('20:398'),Secondary:await figma.getNodeByIdAsync('20:401')};const sidebarComp=await figma.getNodeByIdAsync('20:459');
const auto=shell('automation','自動実行・利用量',4640,5500,'agents');const au=card(auto.body,'Automation settings',1152,20,28,'Paper');const ar=row(au,'Frequency',1096,24);input(ar,'実行頻度','毎日 09:00 · Asia/Tokyo',536);input(ar,'生成する言語','日本語・English',536);input(au,'有効なエージェント','SEO / X / Writer / Reddit',1096);input(au,'実行モード','下書きを作成して確認待ちにする  ⌄',1096);input(au,'利用量の上限','上限を設定してから有効化',1096);const act=between(row(au,'Automation actions',1096));tag(act,'現在：停止中');button(act,'設定を保存');txt(au,'予算・実行数・通知先をワークスペースごとに管理','Caption','muted');
const toolsPage=shell('tools','マーケティングツール',6160,5500,'agents');const tr=card(toolsPage.body,'Utilities',1152,20,28,'Paper');for(const [name,items] of [['文章','Humanizer / メタディスクリプション'],['サイト','メタタグ確認 / robots.txt / sitemap.xml / llms.txt'],['検索','構造化データ / SEO修正'],['配信','UTMビルダー / X動画ダウンロード'],['企画','イベント・ローンチ計画']]){const r=between(row(tr,name,1096,20,12));const c=box(r,'Tool family',840,'VERTICAL',8);txt(c,name,'Label');txt(c,items,'Small','muted');button(r,'開く');}
const render=shell('render','動画の生成を確認',80,6560,'library');const rp=card(render.body,'Render confirmation',1152,20,28,'Paper');txt(rp,'月曜の仕事復帰 / 30秒','Heading');const r1=row(rp,'Render settings',1096,24);input(r1,'出力','9:16 / 720p / MP4',536);input(r1,'音声','日本語 / ナレーションあり',536);txt(rp,'対応比率：9:16・16:9・1:1・4:3・3:4・21:9','Small');txt(rp,'解像度：480p・720p・1080p（生成モデルに依存）','Small','muted');input(rp,'生成指示','手元のシーン、実機デモ、ロゴを組み合わせ、仕事を再開する場面を表現。',1096);tag(rp,'実機デモ素材が必要');txt(rp,'見積りは素材とモデルの確定後に表示されます。','Small','muted');const r2=between(row(rp,'Render actions',1096));button(r2,'台本に戻る','Secondary','video');button(r2,'素材を追加','Primary','context');
const approvalCode=shell('codeApproval','PRの作成を確認',1600,6560,'agents');const ac=card(approvalCode.body,'PR review',1152,20,28,'Paper');txt(ac,'SEO修正 · 新規ブランチにPRを作成','Heading');input(ac,'リポジトリ / ベースブランチ','接続後に選択',1096);input(ac,'変更対象','構造化データ・メタ情報・llms.txt',1096);input(ac,'変更差分・検証結果','リポジトリの解析後に表示',1096);txt(ac,'PRを作成した後も、マージ前にレビューできます。','Small','muted');button(ac,'PR作成用のGitHub接続','Primary','repo');
const creatorReview=shell('creatorReview','クリエイターへの依頼を確認',3120,6560,'agents');const crr=card(creatorReview.body,'Outreach approval',1152,20,28,'Paper');txt(crr,'創業者向け・仕事の再開デモ','Heading');input(crr,'送信先','候補者を選択',1096);const csr=row(crr,'Terms',1096,24);input(csr,'合意金額 / 上限','未確定',536);input(csr,'納期・納品物','X投稿 / 実演動画 / 合意後に確定',536);input(crr,'依頼文','製品を実際に試し、仕事の再開シーンを紹介いただく企画です。',1096);txt(crr,'送信・発注・支払いはそれぞれ承認履歴を記録','Caption','muted');button(crr,'キャンペーンに戻る','Secondary','creators');
const english=(await figma.getNodeByIdAsync('20:830')).clone();page.appendChild(english);english.name='Today / English UI';english.x=4640;english.y=6560;screens.homeEn=english;
const translations={'ShogunAI  /  今日のマーケティング':'ShogunAI  /  Today','今日のマーケティング':'Today','今日':'Today','戦略':'Strategy','コンテンツ':'Content','エージェント':'Agents','カレンダー':'Calendar','分析':'Analytics','製品コンテキスト':'Product context','連携・設定':'Integrations','日本語  /  EN':'English  /  日本語','AIに相談':'Ask AI','設定':'Settings','新しい企画':'New idea','確認待ち':'Needs review','提案を確認':'Review drafts','今週の制作':'This week','コンテンツを開く':'Open content','製品情報':'Product context','1件':'1 update','更新を確認':'Review update','次に進めること':'Next actions','開く':'Open','最近のアクティビティ':'Recent activity','AIに今日の優先順位を聞く':'Ask AI about today','09:40  戦略 v1 を確認\n09:32  製品情報の読み込み完了\n09:30  ワークスペースを作成':'09:40  Strategy v1 reviewed\n09:32  Sources imported\n09:30  Workspace created'};
for(const n of english.findAllWithCriteria({types:['TEXT']})){if(translations[n.characters])n.characters=translations[n.characters];}
// UI locale changes do not silently translate existing draft content.
const enSettings=(await figma.getNodeByIdAsync('22:1417')).clone();page.appendChild(enSettings);enSettings.name='Workspace settings / English UI';enSettings.x=6160;enSettings.y=6560;screens.settingsEn=enSettings;
const t2={...translations,'ShogunAI  /  ワークスペース設定':'ShogunAI / Workspace settings','ワークスペース設定':'Workspace settings','言語・地域':'Language & region','表示言語':'Display language','日本語  ⌄':'English  ⌄','既定の制作言語':'Default content languages','日本語・English':'Japanese · English','対象市場':'Target markets','日本・北米':'Japan · North America','タイムゾーン':'Time zone','メンバー・権限':'Members & access','Toru    オーナー\nデザイナー    招待前':'Toru    Owner\nDesigner    Not invited','メンバーを招待':'Invite member','共有リンク':'Share link','閲覧専用リンクを作成':'Create read-only link','利用量・予算':'Usage & budget','生成・実行ごとに見積りを表示\nワークスペースごとに上限を設定':'Estimate before each run\nSet limits per workspace','利用量・上限を設定':'Usage limits'};
for(const n of enSettings.findAllWithCriteria({types:['TEXT']}))if(t2[n.characters])n.characters=t2[n.characters];
// Material alpha belongs to its own color variable; opaque white aliases erase opacity.
const collection=await figma.variables.getVariableCollectionByIdAsync('VariableCollectionId:20:379');const materialVars={};for(const [k,a] of [['panel',.38],['paper',.9],['control',.5],['edge',.8]]){const v=figma.variables.createVariable('glass/'+k,collection,'COLOR');v.scopes=['FRAME_FILL','SHAPE_FILL','STROKE_COLOR'];v.setValueForMode(collection.defaultModeId,{r:1,g:1,b:1,a});v.setVariableCodeSyntax('WEB','var(--glass-'+k+')');materialVars[k]=v;}
const affected=[];for(const n of page.findAll(n=>'fills'in n&&Array.isArray(n.fills))){if(n.type==='TEXT'||n.type==='VECTOR')continue;let key=null;if(n.effectStyleId===effects.Panel.id)key='panel';else if(n.effectStyleId===effects.Paper.id)key='paper';else if(n.name==='Input'||n.name==='Glass/Button/Secondary')key='control';if(key){n.fills=[figma.variables.setBoundVariableForPaint({type:'SOLID',color:rgb('#ffffff')},'color',materialVars[key])];affected.push(n.id);}if('strokes'in n&&Array.isArray(n.strokes)&&n.strokes.some(p=>p.type==='SOLID'&&p.color.r===1&&p.color.g===1&&p.color.b===1)){n.strokes=[figma.variables.setBoundVariableForPaint({type:'SOLID',color:rgb('#ffffff')},'color',materialVars.edge)];affected.push(n.id);}}
// Recovery details outside the working UI.
const states=card(page,'Source & locale state specifications',1440,24,32,'Paper');states.x=1600;states.y=4400;txt(states,'取り込みと多言語の状態','Title');for(const [title,body] of [['URLを取得できない','再試行 / URLを編集 / この資料を除いて続ける。失敗したURLは一覧に残す。'],['Markdownを読み込めない','ファイル名と原因を表示。対応形式・容量制限をアップロード前に提示。'],['リポジトリの権限が切れた','再接続。最後の取得日時と参照ブランチを表示。読み込みとPR作成の権限を分離。'],['資料が更新された','変更箇所 → 製品理解への影響 → 戦略への影響を比較。手動編集は自動で上書きしない。'],['言語の切り替え','UI言語はユーザー設定。制作言語・対象市場はワークスペース設定。既存原稿は切り替えだけでは翻訳しない。'],['読みやすさ','透明度を下げる設定を用意。本文面は高不透明度。フォーカスは輪郭で表示。色だけで状態を伝えない。']]){txt(states,title,'Label');txt(states,body,'Small','muted',1376);}
const all=page.findAll(()=>true);return {screens:Object.fromEntries(Object.entries(screens).map(([k,n])=>[k,n.id])),statesId:states.id,pendingLinks:links.map(([n,d])=>({id:n.id,to:d})),createdVariableIds:Object.values(materialVars).map(v=>v.id),createdOrAffectedNodeIds:[page.id,...all.map(n=>n.id)],mutatedNodeIds:affected};
