await Promise.all(['Regular','Medium','Bold'].map(style=>figma.loadFontAsync({family:'Noto Sans JP',style})));
const C={ink:'#203A38',muted:'#526863',accent:'#185D52',mint:'#D6F1E3',white:'#FFFFFF',line:'#CEDFD9',canvas:'#EAF2EF',lavender:'#EEEAF8',danger:'#894537'};
const rgb=h=>({r:parseInt(h.slice(1,3),16)/255,g:parseInt(h.slice(3,5),16)/255,b:parseInt(h.slice(5,7),16)/255});
const rgba=(h,a=1)=>({...rgb(h),a});
const tokens=Object.fromEntries((await figma.variables.getLocalVariablesAsync()).filter(v=>v.name.startsWith('glass/')).map(v=>[v.name.slice(6),v]));
const styles=Object.fromEntries((await figma.getLocalTextStylesAsync()).map(s=>[s.name.split('/').pop(),s]));
const effects=Object.fromEntries((await figma.getLocalEffectStylesAsync()).filter(s=>s.name.startsWith('Concentrate Glass/')).map(s=>[s.name.split('/').pop(),s]));
const ids=[],links=[],screens={};
function paint(k,a=1){let p={type:'SOLID',color:rgb(C[k]||k),opacity:a};if(tokens[k])p=figma.variables.setBoundVariableForPaint(p,'color',tokens[k]);return p;}
function txt(p,s,style='Small',color='ink',w){const n=figma.createText();n.fontName={family:'Noto Sans JP',style:'Regular'};n.characters=s;n.name=s.slice(0,50);n.textStyleId=styles[style].id;n.fills=[paint(color)];p.appendChild(n);if(w){n.textAutoResize='HEIGHT';n.resize(w,n.height);}ids.push(n.id);return n;}
function box(p,name,w,dir='VERTICAL',gap=0,pad=0){const n=figma.createAutoLayout(dir);n.name=name;p.appendChild(n);n.resize(w,1);n.primaryAxisSizingMode=dir==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=dir==='VERTICAL'?'FIXED':'AUTO';n.fills=[];n.itemSpacing=gap;for(const k of ['paddingTop','paddingBottom','paddingLeft','paddingRight'])n[k]=pad;ids.push(n.id);return n;}
function row(p,name,w,gap=12,pad=0){const n=box(p,name,w,'HORIZONTAL',gap,pad);n.counterAxisAlignItems='CENTER';return n;}
function between(n){n.primaryAxisAlignItems='SPACE_BETWEEN';return n;}
function fixed(n,w,h){n.resize(w,h);n.primaryAxisSizingMode='FIXED';n.counterAxisSizingMode='FIXED';return n;}
function glass(n,material='Panel'){n.cornerRadius=24;n.fills=[paint('white',material==='Paper'?.90:.58)];n.strokes=[paint('white',.9)];n.strokeWeight=1;n.effectStyleId=effects[material].id;return n;}
function card(p,name,w,gap=16,pad=24,material='Panel'){return glass(box(p,name,w,'VERTICAL',gap,pad),material);}
function tag(p,label,active=false){const n=row(p,'Tag / '+label,100,0,6);n.primaryAxisSizingMode='AUTO';n.cornerRadius=10;n.fills=[paint(active?'mint':'white',active?.9:.64)];txt(n,label,'Caption',active?'accent':'muted');return n;}
function button(p,label,kind='Secondary',dest){const c=buttonComps[kind],n=c.createInstance();p.appendChild(n);n.setProperties({[Object.keys(c.componentPropertyDefinitions)[0]]:label});ids.push(n.id);if(dest)links.push([n,dest]);return n;}
function input(p,label,value,w){const n=box(p,'Field / '+label,w,'VERTICAL',8);txt(n,label,'Label');const v=box(n,'Input',w,'VERTICAL',0,14);v.cornerRadius=12;v.fills=[paint('white',.78)];v.strokes=[paint('line')];txt(v,value,'Small','ink',w-28);return n;}
function icon(p,name,size=20,color='accent'){const n=figma.createNodeFromSvg(SOURCE.icons[name].replaceAll('currentColor',C[color]));p.appendChild(n);n.resize(size,size);n.name='Icon/'+name;ids.push(n.id,...n.findAll(()=>true).map(n=>n.id));return n;}
function bg(n){n.fills=[{type:'GRADIENT_LINEAR',gradientTransform:[[.8,.5,0],[-.5,.8,.4]],gradientStops:[{position:0,color:rgba('#DEF1E8')},{position:.5,color:rgba('#EDF2F4')},{position:1,color:rgba('#E7E2F5')}]}];}
function base(key,title,x,y){const n=box(page,title,1440,'HORIZONTAL',24,24);fixed(n,1440,960);n.x=x;n.y=y;n.clipsContent=true;bg(n);screens[key]=n;return n;}
function stepbar(p,step){const n=row(p,'Onboarding steps',880,24);['情報を追加','内容を確認','目標を設定','戦略を確認'].forEach((s,i)=>{const t=txt(n,String(i+1)+'  '+s,'Label',i===step?'accent':'muted');if(i===step)t.textDecoration='UNDERLINE';});return n;}
function onboard(key,title,step,x,y){const root=base(key,title,x,y);root.layoutMode='VERTICAL';root.itemSpacing=28;const h=glass(between(row(root,'Onboarding header',1392,24,20)));const logo=row(h,'Logo',330,10);icon(logo,'FlaskConical',22);txt(logo,'concentrate','Heading');button(h,'保存して終了','Secondary','workspaces');const wrap=box(root,'Onboarding layout',1392,'VERTICAL',28,20);wrap.counterAxisAlignItems='CENTER';const content=box(wrap,'Onboarding content',960,'VERTICAL',24);if(step>=0)stepbar(content,step);txt(content,title,'Title');return {root,content};}
function shell(key,title,x,y,active='home'){const root=base(key,title,x,y);const si=sidebarComp.createInstance();root.appendChild(si);si.resize(216,912);ids.push(si.id);links.push([si.findOne(n=>n.name==='Workspace switcher'),'workspaces']);for(const [label,dest] of [['今日','home'],['戦略','strategy'],['コンテンツ','library'],['エージェント','agents'],['カレンダー','calendar'],['分析','analytics'],['製品コンテキスト','context'],['連携・設定','integrations']]){const n=si.findOne(n=>n.name==='Nav / '+label);if(dest===active){n.fills=[paint('white',.85)];n.strokes=[paint('white')];}else links.push([n,dest]);}
const main=box(root,'Main',1152,'VERTICAL',24);const top=glass(between(row(main,'Workspace bar',1152,20,16)));txt(top,'ShogunAI  /  '+title,'Small');const actions=row(top,'Utilities',260,12);button(actions,'AIに相談','Secondary','chat');button(actions,'設定','Secondary','settings');const head=between(row(main,'Page heading',1152,20));txt(head,title,'Title');const body=box(main,'Content',1152,'VERTICAL',20);return {root,main,head,body};}
function nav(n,d){links.push([n,d]);return n;}
async function connect(){for(const [n,key] of links){const to=screens[key]||await figma.getNodeByIdAsync(EXISTING[key]);let top=n;while(top.parent&&top.parent!==page)top=top.parent;if(top===to)continue;await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'NODE',destinationId:to.id,navigation:'NAVIGATE',transition:null}]}]);}}
