const sg=await state('20:722','strategyGenerated','原液の候補',42);text(sg.pane,'原液の候補','Heading');for(const [t,v]of [['月曜の仕事復帰','創業者 / ユースケース'],['AIへの背景説明','PM / 機能便益']]){const p=panel(sg.pane,t,772,10,16);text(p,t,'Card title');text(p,v,'Caption','muted');field(p,'企画メモ','仕事の再開に必要な文脈を取り戻す',740);}button(sg.pane,'候補をコンテンツに保存','strategySaved',true);
const aw=await state('22:631','agentWriting','Writer 原稿',43);text(aw.pane,'原液の下書き','Heading');field(aw.pane,'タイトル','月曜の朝、金曜の自分に聞けたら。',824);field(aw.pane,'本文','仕事を再開するときに必要なのは、前回の判断とその理由。何を決め、何が残ったかが分かれば、次の一歩を踏み出せる。',824);const awr=row(aw.pane,'Writer result actions',824);button(awr,'コンテンツに保存','agentSaved',true);button(awr,'変更案を作る','assistant');
const social=await state('22:631','agentSocialResult','投稿の原稿',44);text(social.pane,'Xの原稿','Heading');field(social.pane,'本文','月曜の朝、最初の仕事が「先週の仕事を思い出すこと」になっていませんか。',824);field(social.pane,'投稿先','X / @shogunai_demo',824);field(social.pane,'日時','2026/10/05 09:00 · Asia/Tokyo',824);button(social.pane,'原稿を保存','agentSaved',true);button(social.pane,'予約内容を確認','agentSchedule');
for(const [key,month,offset,count,index]of [['calendarSeptember',9,1,30,45],['calendarNovember',11,6,30,46]]){
const src=await figma.getNodeByIdAsync('22:1085');const n=src.clone();page.appendChild(n);n.name='カレンダー / '+month+'月';n.x=80+(index%5)*1520;n.y=7900+Math.floor(index/5)*1060;states[key]=n.id;created.push(n.id,...n.findAll(x=>!x.id.startsWith('I')).map(x=>x.id));const grid=n.findOne(x=>x.name==='Calendar grid');clear(grid);const header=row(grid,'Days of week',768,0);for(const d of ['月','火','水','木','金','土','日'])text(header,d,'Caption','muted',109.7);const weeks=Math.ceil((offset+count)/7);for(let week=0;week<weeks;week++){const r=row(grid,'Week '+week,768,0);for(let d=0;d<7;d++){const date=week*7+d-offset+1,c=box(r,'Day / '+date,109.7,'VERTICAL',7,7);fixed(c,109.7,580/weeks);c.strokes=[paint('line')];c.strokeWeight=.5;text(c,date<1?String(date+31):date>count?String(date-count):String(date),'Label',date<1||date>count?'muted':'ink');target(c,'calendarNew');}}text(grid,'Asia/Tokyo','Caption','muted');for(const t of n.findAll(x=>x.type==='TEXT'))if(t.characters==='2026年10月'){t.characters='2026年'+month+'月';mutated.push(t.id);}const inspector=n.findOne(x=>x.name==='Post inspector');clear(inspector);text(inspector,'日付を選択','Card title');text(inspector,'予定を選択するか、日付をクリックして追加できます。','Small','muted',300);button(inspector,'予定を追加','calendarNew',true);for(const a of n.findAll(x=>x.name==='Action / ‹'||x.name==='Action / ›'))target(a,'calendar');}
const preview=panel(page,'Overlay / 記事プレビュー',720,20,28);preview.x=10800;preview.y=11400;states.contentPreview=preview.id;const ph=between(row(preview,'Preview heading',664));text(ph,'記事プレビュー','Heading');button(ph,'閉じる','__close');text(preview,'仕事を再開するために、何を残しておくべきか','Heading','ink',664);text(preview,'決定だけでなく、判断した理由を残す。\n\n週をまたいだ仕事の再開には、タスク一覧だけでは足りないことがある。前回の論点と残された問いを短くまとめておきたい。','Body','ink',664);
const board=panel(page,'Interaction contract / Not product UI',1440,24,32);board.x=8000;board.y=12200;states.interactionSpec=board.id;text(board,'Interaction contract','Display');
for(const [title,body]of [
['作業の場所','一覧・選択・編集を同じタブに保持。詳細は右ペイン、短い入力はポップオーバー。確認だけの別ページを作らない。戻ると選択・スクロール・フィルター・入力内容を復元。'],
['起動と待ち時間','起動スプラッシュはセッション未確定時のみ。意図的な最低表示時間なし。通常のタブ移動ではシェルを保持。300ms以上で対象領域にスケルトン。10秒以上は再試行・接続確認。進捗は実測のみ。'],
['保存と競合','入力を即時保持し、800msの入力停止後に保存。未保存→保存中→保存済み。失敗時は原稿を残し再試行・コピー。別端末の更新は差分確認。未保存で離脱するときだけ確認する。'],
['カレンダー','月・週・今日、媒体・状態の絞り込み。日付クリックで予定を作成。ドラッグは日時変更の確認を出してから保存。公開直前の変更不可時は理由を表示。過去日時・夏時間・タイムゾーンを検証する。'],
['接続と公開','OAuthは外部認証後、元のタブに戻る。サービス・アカウント・権限・ワークスペースを確認。接続切れは予約を保留。送信結果不明は外部投稿IDを照合し、二重投稿を避ける。'],
['操作とアクセシビリティ','Hover 120ms / 押下は即時 / ペイン 180ms。prefers-reduced-motion は動きを省略。常時キーボード操作可。Escで閉じ、フォーカスを起点へ戻す。モーダル内はフォーカスを保持。状態変化を読み上げる。'],
['プロトタイプの読み方','同じタブの複数フレームは状態例。別ルートへの遷移を意味しない。認証・アップロード・生成・保存・公開は実行しない。数値・アカウントはデモ。タイミング値は実装時の要件。']]){text(board,title,'Card title');text(board,body,'Body','muted',1376);}
const br=row(board,'Button states',1376,24);for(const [label,kind]of [['通常','normal'],['ホバー','hover'],['フォーカス','focus'],['保存中…','busy'],['実行できません','disabled']]){const b=button(br,label,null,true);if(kind==='hover')b.opacity=.9;if(kind==='focus'){b.strokes=[paint('accent')];b.strokeWeight=3;b.strokeAlign='OUTSIDE';}if(kind==='disabled')b.opacity=.4;}
return {...result(),overlays:[preview.id]};
