let serial=0;async function fresh(key,title,base='61:6361'){const s=await root(base,key,title,true);s.n.x=25400+(serial%4)*1520;s.n.y=80+Math.floor(serial++/4)*1060;return s;}
function idbar(p,label){const r=between(row(p,'Review context',1152));text(r,'月曜の仕事復帰','Heading');text(r,'E-001 / '+label,'Small','muted');}
for(const [key,label,before,after,impact,back]of [
['review','日本語 · 動画 v3 · シーン02','前回、何を決めて、なぜそう決めたのか。','前回の判断と、その理由を。','音声・字幕・同期点を更新。締めの文言は維持。','video'],
['guideReview','日本語 · 手順書 v3 · 手順2','前回の判断と理由を確認します。','決定事項を開き、その理由と残った論点を確認します。','手順2の本文のみ。動画・音声は変更しません。','guide'],
['planReview','企画 v2 · 導入','困る瞬間 5秒 → 実演 13秒 → 次の作業 7秒 → CTA 5秒','困る瞬間 3秒 → 実演 15秒 → 次の作業 7秒 → CTA 5秒','計画のみ更新。制作済みの動画は保持。','plan'],
['localeReview','English · 16:9 · v1 · Scene 02','What did we decide, and why?','Our last decision, and the reason behind it.','英語の音声・字幕のみ。日本語版は保持。','locales']]){const s=key==='review'?await root('61:6361',key,'コンテンツ / 変更レビュー'):await fresh(key,'コンテンツ / '+label);idbar(s.body,label);const [a,b]=split(s.body,742,390);text(a,'変更内容を確認','Heading');field(a,'現在',before,702);field(a,'変更案',after,702);note(a,'影響する範囲',impact,702);const r=row(a,'Review actions',702);button(r,'適用する',key+'Applied',true);button(r,'破棄して戻る',back);text(b,'追加の指示','Card title');field(b,'同じ対象に指示する','もう少し自然な言い方に',350);button(b,'この対象で再生成',key+'Generating');text(b,'他の成果物・言語版は変更しません。','Small','muted',350);}
const m=await fresh('measurement','分析 / 計測設定','22:1197');idbar(m.body,'計測設定');const [ml,mr]=split(m.body,742,390);text(ml,'初回の価値体験を定義','Heading');field(ml,'イベント名','context_answer_used（候補・未確定）',702);field(ml,'計測する行動','過去の文脈を取得し、仕事で役立つ結果を利用した',702);field(ml,'施策パラメータ','utm_campaign = resume-work',702);text(ml,'イベントの実装・発火確認が終わるまで、成果には集計しません。','Small','muted',702);button(ml,'GA4の接続設定へ','integrations',true);button(ml,'分析に戻る','analytics');text(mr,'計測の状態','Heading');badge(mr,'未接続');text(mr,'接続 → イベント確認 → テスト流入 → 集計','Body','ink',350);
const meet=await fresh('meeting','コンテンツ / 会議5分前','22:767');const mh=between(row(meet.body,'Content identity',1152));text(mh,'会議5分前','Heading');badge(mh,'企画 · E-002');const [me,mi]=split(meet.body,742,390);text(me,'前回の「なぜ」を取り戻す。','Title');text(me,'前回の決定、判断の理由、残った論点を確認してから会議に入る。','Body','ink',702);field(me,'具体シーン','会議の直前に、前回の議事録と決定理由を探している。',702);note(me,'実演は準備中','この企画の動画はまだありません。別の企画の動画には切り替えません。',702);button(me,'一覧へ戻る','content');text(mi,'制作状況','Heading');text(mi,'原稿：下書き\n動画：未制作\n手順書：未制作','Body','ink',350);
return result();
