let serial=0;async function cloneScreen(id,key){const n=(await figma.getNodeByIdAsync(id)).clone();page.appendChild(n);n.x=25400+(serial%4)*1520;n.y=2400+Math.floor(serial++/4)*1060;n.name='確認状態 / '+key;created.push(n.id,...n.findAll(x=>!x.id.startsWith('I')).map(x=>x.id));states[key]=n.id;return n;}
async function replace(n,before,after){for(const t of n.findAllWithCriteria({types:['TEXT']})){if(t.characters===before){await Promise.all(t.getStyledTextSegments(['fontName']).map(s=>figma.loadFontAsync(s.fontName)));t.characters=after;mutated.push(t.id);}}}
for(const [num,line,range]of [['01','月曜の朝、前回の判断を探していませんか。','00:00 – 00:05'],['03','残った論点を確認して、次の作業へ。','00:18 – 00:25'],['04','ShogunAIを、自分の仕事で試す。','00:25 – 00:30']]){const n=await cloneScreen('36:2381','scene'+num);await replace(n,'シーン02','シーン'+num);await replace(n,'前回、何を決めて、なぜそう決めたのか。',line);await replace(n,'00:05 – 00:18',range);const ins=n.findOne(x=>x.name==='Inspector');const ai=ins.findOne(x=>x.name==='Action / 変更案を確認');ai.remove();for(const b of n.findOne(x=>x.name==='Scene list').children){if(b.type==='INSTANCE')b.fills=[paint(b.name.startsWith('Action / '+num)?'mint':'white')];}}
for(const [key,id,before,after]of [['reviewApplied','36:2381','前回、何を決めて、なぜそう決めたのか。','前回の判断と、その理由を。'],['guideReviewApplied','60:5634','前回の判断と理由を確認します。','決定事項を開き、その理由と残った論点を確認します。'],['planReviewApplied','60:5167','01  月曜の朝、前回の判断を探す','01  導入を3秒に短縮して実演へ'],['localeReviewApplied','60:5808','What did we decide, and why?','Our last decision, and the reason behind it.']]){const n=await cloneScreen(id,key);await replace(n,before,after);const body=n.findOne(x=>x.name==='Content');badge(body,'変更を適用済み · プロトタイプ');}
for(const [key,title,detail,back]of [['reviewGenerating','動画の変更案を生成中','シーン02 · 台本を調整しています','review'],['guideReviewGenerating','手順の変更案を生成中','手順2 · 本文のみを調整しています','guideReview'],['planReviewGenerating','計画の変更案を生成中','導入と実演の時間配分を調整しています','planReview'],['localeReviewGenerating','英語版の変更案を生成中','English / Scene 02 · 字幕と音声','localeReview']]){const s=await root('61:6361',key,'コンテンツ / 生成中',true);s.n.x=25400+(serial%4)*1520;s.n.y=2400+Math.floor(serial++/4)*1060;const p=panel(s.body,'Job',1152,20,32);text(p,title,'Heading');text(p,detail,'Body');text(p,'作業を続けても、ここから再開できます。','Small','muted');const r=row(p,'Job actions',1088);button(r,'キャンセルして戻る',back);button(r,'完了状態を確認',back,true);button(r,'失敗状態を確認','failure');}
const f=await root('61:6361','failure','コンテンツ / 生成エラー',true);f.n.x=25400+(serial%4)*1520;f.n.y=2400+Math.floor(serial++/4)*1060;const fp=panel(f.body,'Failure',1152,20,32);text(fp,'生成を完了できませんでした','Heading');text(fp,'接続が中断されました。元の制作物と入力した指示は保持されています。','Body','ink',1088);button(fp,'再試行','reviewGenerating',true);button(fp,'動画へ戻る','video');
const aspect=await root('60:5808','aspect','コンテンツ / 比率を選択',true);aspect.n.x=25400+(serial%4)*1520;aspect.n.y=2400+Math.floor(serial++/4)*1060;text(aspect.body,'月曜の仕事復帰 / 日本語','Heading');button(aspect.body,'16:9 · 横動画','video');button(aspect.body,'9:16 · 縦動画','portrait');
for(const [key,en]of [['portrait',false],['englishPortrait',true]]){const n=await cloneScreen('36:2381',key);await replace(n,'E-001  /  日本語 · v3',en?'E-001 / English · 9:16 · 未生成':'E-001 / 日本語 · 9:16 · 配置確認');const p=n.findOne(x=>x.name==='Media preview');p.resize(194,346);const center=n.findOne(x=>x.name==='Preview and timeline');center.counterAxisAlignItems='CENTER';await replace(n,'前回、何を決めて、なぜそう決めたのか。',en?'Our last decision, and the reason behind it.':'前回の判断と、その理由を。');if(en){p.fills=[paint('canvas')];text(p,'英語版は未生成','Small','muted',180);}const ins=n.findOne(x=>x.name==='Inspector');const ai=ins.findOne(x=>x.name==='Action / 変更案を確認');ai.remove();button(ins,'言語版へ戻る','locales');}
return result();
