// Source-derived native Figma sync. Run only after inspecting existing IDs.
await figma.setCurrentPageAsync(await figma.getNodeByIdAsync('20:391'));
await Promise.all(['Regular','Medium','Bold'].map(style=>figma.loadFontAsync({family:'Noto Sans JP',style})));
const page=figma.currentPage,created=[],screens={},links=[];
const vars=Object.fromEntries((await figma.variables.getLocalVariablesAsync()).map(v=>[v.name,v]));
const styles=Object.fromEntries((await figma.getLocalTextStylesAsync()).map(s=>[s.name.split('/').pop(),s]));
const primary=await figma.getNodeByIdAsync('20:398'),secondary=await figma.getNodeByIdAsync('20:401'),fieldComp=await figma.getNodeByIdAsync('5:346');
function paint(k){return figma.variables.setBoundVariableForPaint({type:'SOLID',color:{r:1,g:1,b:1}},'color',vars['glass/'+k]);}
function space(n,k,v){n[k]=v;const t=vars['spacing/'+v];if(t)n.setBoundVariable(k,t);}
function box(p,name,w,dir='VERTICAL',gap=16,pad=0){const n=figma.createAutoLayout(dir);p.appendChild(n);created.push(n.id);n.name=name;n.resize(w,1);n.primaryAxisSizingMode=dir==='VERTICAL'?'AUTO':'FIXED';n.counterAxisSizingMode=dir==='VERTICAL'?'FIXED':'AUTO';n.fills=[];space(n,'itemSpacing',gap);for(const k of ['paddingLeft','paddingRight','paddingTop','paddingBottom'])space(n,k,pad);return n;}
function text(p,s,style='Small',color='ink',width){const n=figma.createText();p.appendChild(n);created.push(n.id);n.fontName={family:'Noto Sans JP',style:'Regular'};n.characters=s;n.textStyleId=styles[style].id;n.fills=[paint(color)];n.name=s.slice(0,45);if(width){n.textAutoResize='HEIGHT';n.resize(width,n.height);}return n;}
function button(p,s,main=false,dest){const c=main?primary:secondary,n=c.createInstance();p.appendChild(n);created.push(n.id);n.setProperties({[Object.keys(c.componentPropertyDefinitions)[0]]:s});if(dest)links.push([n,dest]);return n;}
function panel(p,name,w){const n=box(p,name,w,'VERTICAL',18,22);n.fills=[paint('white')];n.strokes=[paint('line')];n.cornerRadius=16;return n;}
function field(p,label,value,w,tall=false){const n=fieldComp.createInstance();p.appendChild(n);created.push(n.id);n.setProperties({'Label#5:32':label,'Value#5:33':value||' '});n.resize(w,n.height);const v=n.findAllWithCriteria({types:['TEXT']});for(const t of v){t.textAutoResize='HEIGHT';t.resize(w-28,t.height);}const input=n.children.find(n=>n.type==='FRAME');if(input){input.resize(w,tall?160:44);input.primaryAxisSizingMode='FIXED';input.counterAxisSizingMode='FIXED';input.cornerRadius=9;}return n;}
const nav=[['今日','home','House'],['戦略','strategy','Target'],['コンテンツ','content','FileText'],['エージェント','agents','Waypoints'],['カレンダー','calendar','CalendarDays'],['分析','analytics','ChartNoAxesCombined'],['製品コンテキスト','context','BookOpen'],['インテグレーション','integrations','Plug'],['設定','settings','Settings']];
const old=await figma.getNodeByIdAsync('20:459');const sidebar=old.clone();page.appendChild(sidebar);sidebar.name='Implementation/Sidebar';sidebar.x=0;sidebar.y=23700;created.push(sidebar.id);for(const child of [...sidebar.children])child.remove();sidebar.resize(216,912);sidebar.fills=[{type:'SOLID',color:{r:20/255,g:44/255,b:35/255}}];sidebar.effects=[];sidebar.cornerRadius=20;sidebar.itemSpacing=10;sidebar.paddingTop=22;sidebar.paddingLeft=14;sidebar.paddingRight=14;sidebar.paddingBottom=22;
text(sidebar,'♧  Concentrate','Heading','white');text(sidebar,'ワークスペース','Caption','white');text(sidebar,'ShogunAI　⌄','Label','white');
for(const [label,key,icon] of nav){const r=box(sidebar,'Nav / '+key,188,'HORIZONTAL',12,10);r.resize(188,44);r.primaryAxisSizingMode='FIXED';r.counterAxisSizingMode='FIXED';r.counterAxisAlignItems='CENTER';const svg=figma.createNodeFromSvg(ICONS[icon]);r.appendChild(svg);svg.resize(18,18);created.push(svg.id,...svg.findAll(()=>true).map(n=>n.id));text(r,label,'Small','white');}
text(sidebar,'ShogunAI team　·　owner','Caption','white');text(sidebar,'日本語　⌄','Small','white');
const note=box(page,'Implementation / readme',1440,'VERTICAL',12,24);note.x=300;note.y=23500;note.fills=[paint('mint')];text(note,'実装済みUI · 2026-10-02','Title');text(note,'ワークスペース・資料・企画・原稿・シーン・版履歴・公開予定は永続保存。AIはサーバー設定後に有効。外部投稿・動画レンダー・計測・MCP/CLI・招待・課金は未接続。上段の製品設計は保持。','Body','ink',1392);
function shell(key,title,index){const root=box(page,'Implemented / '+title,1440,'HORIZONTAL',24,24);root.x=300+(index%3)*1540;root.y=24000+Math.floor(index/3)*1120;root.resize(1440,1020);root.primaryAxisSizingMode='FIXED';root.counterAxisSizingMode='FIXED';root.fills=[paint('canvas')];root.clipsContent=true;screens[key]=root;const si=sidebar.createInstance();root.appendChild(si);created.push(si.id);for(const [label,dest] of nav){const r=si.findOne(n=>n.name==='Nav / '+dest);if(r)links.push([r,dest]);}const main=box(root,'Main',1152,'VERTICAL',22);text(main,'ShogunAI　 /　'+title+'　　　　　　　　　　　　　保存済み','Small','muted');const head=box(main,'Page heading',1152,'HORIZONTAL',16);head.primaryAxisAlignItems='SPACE_BETWEEN';text(head,title,'Title');if(['strategy','calendar','analytics'].includes(key))button(head,'保存する',true);return {root,main,head,body:box(main,'Content',1152,'VERTICAL',20)};}
function tabs(p,active='原稿'){const r=box(p,'Content tabs',1152,'HORIZONTAL',8);for(const s of ['企画','原稿','X','記事','Reddit','動画','手順書','言語版','素材','更新','変更案']){const t=text(r,s,'Small',s===active?'accent':'muted');if(s==='動画')links.push([t,'video']);else if(s==='原稿')links.push([t,'content']);}return r;}
let s=shell('home','今日',0);text(s.body,'次の企画を、形に。','Display');text(s.body,'1件の企画　·　1件の資料','Small','muted');button(s.head,'新しい企画',true,'content');let row=box(s.body,'Home panels',1152,'HORIZONTAL',20);let a=panel(row,'Continue',566);text(a,'制作を続ける','Heading');button(a,'月曜の仕事復帰　v2 · 7項目',false,'content');let b=panel(row,'Setup',566);text(b,'制作の準備','Heading');button(b,'製品コンテキスト　1件',false,'context');button(b,'インテグレーション　AI設定待ち',false,'integrations');button(b,'カレンダー',false,'calendar');
s=shell('strategy','戦略',1);row=box(s.body,'Strategy fields',1152,'HORIZONTAL',20);a=panel(row,'Message',566);field(a,'企画名','月曜の仕事復帰',522);field(a,'届ける相手','複数案件を進めるPM',522);field(a,'解決したい課題','前回の判断を探してから仕事を再開している',522,true);field(a,'伝える主張','前回の文脈から、仕事を続ける',522);b=panel(row,'Experiment',566);field(b,'検証する仮説','月曜朝の共感から、製品の体験へつながるか',522,true);field(b,'CTA','ShogunAIを試す',522);field(b,'遷移先URL','https://shogunaios.com/ja',522);field(b,'評価指標','登録率・初回成功率・翌週再利用率',522);field(b,'評価日','未設定',522);button(b,'原稿を編集',true,'content');
s=shell('content','コンテンツ',2);tabs(s.body);text(s.body,'月曜の仕事復帰　 /　v2 · 保存済み','Heading');row=box(s.body,'Draft editor',1152,'HORIZONTAL',20);a=panel(row,'Selection',280);field(a,'タイトル・本文で検索','',236);button(a,'月曜の仕事復帰',false,'content');button(a,'＋ 項目を追加');b=panel(row,'Editor',852);field(b,'タイトル','原稿',808);field(b,'本文','月曜の朝、金曜の自分に聞けたら。\n前回の判断と文脈から、仕事を再開する。',808,true);button(b,'編集をロック');field(b,'AIへの指示','',808,true);button(b,'変更案を生成',true);text(b,'AI生成はサーバー設定待ちです。','Caption','muted');
s=shell('video','コンテンツ / 動画',3);tabs(s.body,'動画');text(s.body,'月曜の仕事復帰　 /　v2 · 保存済み','Heading');row=box(s.body,'Video workbench',1152,'HORIZONTAL',18);a=panel(row,'Scenes',200);for(const name of ['01 困る瞬間','02 前回の判断','03 次の作業','04 試してみる'])button(a,name);b=box(row,'Preview',598,'VERTICAL',16);const media=figma.createRectangle();b.appendChild(media);created.push(media.id);media.resize(598,337);media.fills=[{type:'IMAGE',imageHash:'fb8e9e0fabdb797329983993a340088e5dfa9519',scaleMode:'FIT'}];media.cornerRadius=16;text(b,'参考素材 · 2026-09-06 · 実収録ではありません','Caption','muted');button(b,'プレビューを拡大');text(b,'ストーリーボード · 秒数は未設定','Small','muted');text(b,'01 困る瞬間　→　02 前回の判断　→　03 次の作業','Small');const c=panel(row,'Script',318);field(c,'タイトル','困る瞬間',274);field(c,'台本','前回の判断を探していませんか。',274,true);button(c,'編集をロック');field(c,'AIへの指示','',274,true);button(c,'変更案を生成',true);text(c,'AI生成はサーバー設定待ちです。','Caption','muted',274);
s=shell('context','製品コンテキスト',4);row=box(s.body,'Sources',1152,'HORIZONTAL',20);a=panel(row,'Add source',566);text(a,'資料を追加','Heading');field(a,'資料の種類','Markdown / Text　⌄',522);field(a,'資料名','ShogunAI positioning',522);button(a,'MDファイルを読み込む');field(a,'参照する本文','製品情報・ブランドの方針を入力',522,true);button(a,'資料を保存',true);b=panel(row,'Saved sources',566);text(b,'登録済みの資料','Heading');text(b,'ShogunAI positioning　 /　markdown','Label');text(b,'URL・Repositoryは参照先と本文を保存。自動取得は未接続。','Small','muted',522);
s=shell('calendar','カレンダー',5);text(s.body,'←　2026年10月　→　　公開予定 · 自動投稿は未接続','Heading');const cal=panel(s.body,'Month grid',1152);row=box(cal,'Weekdays',1108,'HORIZONTAL',1);for(const d of ['月','火','水','木','金','土','日'])text(row,d,'Small','muted',157);for(let week=0;week<5;week++){row=box(cal,'Week '+week,1108,'HORIZONTAL',1);for(let d=0;d<7;d++){const n=week*7+d-2,cell=box(row,'Calendar day '+n,157,'VERTICAL',6,8);cell.resize(157,84);cell.primaryAxisSizingMode='FIXED';cell.counterAxisSizingMode='FIXED';cell.strokes=[paint('line')];text(cell,n>0&&n<=31?String(n):' ','Small');if(n===5)text(cell,'月曜の仕事復帰','Caption','accent',140);}}field(s.body,'公開予定日','2026-10-05',522);
s=shell('integrations','インテグレーション',6);for(const names of [['AI','Markdown'],['URL / GitHub','X / Reddit / YouTube'],['Video / Voice / Export','MCP / CLI']]){row=box(s.body,'Integration row',1152,'HORIZONTAL',20);for(const name of names){a=panel(row,name,566);text(a,name,'Heading');text(a,name==='Markdown'?'利用可能':'未接続','Label');text(a,name==='AI'?'サーバー設定後に有効':name==='Markdown'?'資料本文の読み込み・保存':'接続口・外部実行は未実装','Small','muted');}}
s=shell('analytics','分析',7);a=panel(s.body,'Measurement status',1152);text(a,'計測は未接続です','Heading');text(a,'実績データはまだありません。','Small','muted');a=panel(s.body,'Decision record',1152);field(a,'評価指標','登録率・初回成功率・翌週再利用率',1108);field(a,'評価日','未設定',1108);field(a,'検証結果・次の判断','',1108,true);
s=shell('settings','設定',8);row=box(s.body,'Settings panels',1152,'HORIZONTAL',20);a=panel(row,'Account',566);text(a,'アカウント','Heading');text(a,'ChatGPT 認証','Label');field(a,'表示言語','日本語　⌄',522);text(a,'チーム招待と課金は未接続です。','Small','muted');b=panel(row,'Workspace create',566);text(b,'ワークスペースを追加','Heading');field(b,'製品・ブランド名','',522);button(b,'作成',true,'context');text(b,'資料と原稿はワークスペースごとに分離されます。','Small','muted',522);
s=shell('agents','エージェント',9);a=panel(s.body,'Proposal status',1152);text(a,'AIの変更案','Heading');text(a,'生成結果は確認後に適用します。原稿を自動で上書きしません。','Small','muted');button(a,'変更案を確認',true,'content');
for(const [n,dest] of links){let top=n;while(top.parent&&top.parent!==page)top=top.parent;if(screens[dest]&&top.id!==screens[dest].id)await n.setReactionsAsync([{trigger:{type:'ON_CLICK'},actions:[{type:'NODE',destinationId:screens[dest].id,navigation:'NAVIGATE',transition:null}]}]);}
const fonts=[...new Set(Object.values(screens).flatMap(f=>f.findAllWithCriteria({types:['TEXT']}).map(t=>t.fontName.family)))];
return {screenIds:Object.fromEntries(Object.entries(screens).map(([k,v])=>[k,v.id])),sidebarId:sidebar.id,noteId:note.id,createdNodeIds:created,fonts,counts:Object.fromEntries(Object.entries(screens).map(([k,v])=>[k,{text:v.findAllWithCriteria({types:['TEXT']}).length,instances:v.findAllWithCriteria({types:['INSTANCE']}).length}]))};
