// Run via use_figma after loading the Figma skills. SOURCE is injected from source.json.
const page=await figma.getNodeByIdAsync('0:1');await figma.setCurrentPageAsync(page);
await Promise.all(['Regular','Medium','Bold'].map(style=>figma.loadFontAsync({family:'Noto Sans JP',style})));
const ids=[],createdVars=[],styles={},tokens={},components={};
const prior=page.children.find(n=>n.name==='AI Concentrate / Implementation v1');if(prior)throw new Error('Already exists: inspect the ledger and update in place.');
function rgb(hex){return {r:parseInt(hex.slice(1,3),16)/255,g:parseInt(hex.slice(3,5),16)/255,b:parseInt(hex.slice(5,7),16)/255}}
async function createVariableCollection(name,modeNames){const collection=figma.variables.createVariableCollection(name);const modeIds={};const first=collection.modes[0];collection.renameMode(first.modeId,modeNames[0]);modeIds[modeNames[0]]=first.modeId;for(let i=1;i<modeNames.length;i++)modeIds[modeNames[i]]=collection.addMode(modeNames[i]);return {collection,modeIds}}
const {collection:prims}=await createVariableCollection('Concentrate / Primitives',['Value']);const {collection:sem}=await createVariableCollection('Concentrate / Semantic',['Value']);
const colors={ink:'#182a24',muted:'#6f7a74',line:'#e2e7e3',green:'#173e30',lime:'#d6f887',surface:'#f6f8f5',white:'#ffffff',sidebar:'#142c23',subtle:'#f0f5e9',feature:'#1d402f',onDark:'#e5ece6',darkMuted:'#b3c4b9',input:'#fcfdfb'};
for(const [k,h] of Object.entries(colors)){const p=figma.variables.createVariable('color/'+k,prims,'COLOR');p.scopes=[];p.setValueForMode(prims.defaultModeId,rgb(h));p.setVariableCodeSyntax('WEB',`var(--primitive-${k})`);const v=figma.variables.createVariable('color/'+k,sem,'COLOR');v.scopes=['FRAME_FILL','SHAPE_FILL','TEXT_FILL','STROKE_COLOR'];v.setValueForMode(sem.defaultModeId,{type:'VARIABLE_ALIAS',id:p.id});v.setVariableCodeSyntax('WEB',`var(--${k})`);tokens[k]=v;createdVars.push(p.id,v.id)}
for(const n of [4,5,6,7,8,9,10,12,13,14,15,16,17,18,20,21,22,23,24,25,27,28,29,30,32,35,36,40,42,48,60]){const v=figma.variables.createVariable('spacing/'+n,sem,'FLOAT');v.scopes=['GAP'];v.setValueForMode(sem.defaultModeId,n);v.setVariableCodeSyntax('WEB',`var(--space-${n})`);tokens['s'+n]=v;createdVars.push(v.id)}
for(const n of [4,5,6,8,10]){const v=figma.variables.createVariable('radius/'+n,sem,'FLOAT');v.scopes=['CORNER_RADIUS'];v.setValueForMode(sem.defaultModeId,n);v.setVariableCodeSyntax('WEB',`var(--radius-${n})`);tokens['r'+n]=v;createdVars.push(v.id)}
function paint(key){return figma.variables.setBoundVariableForPaint({type:'SOLID',color:rgb(colors[key]||key)},'color',tokens[key]||tokens.ink)}
function fill(n,key){n.fills=key?[paint(key)]:[]}
for(const [name,size,weight,line] of [['Display',34,'Bold',49],['Title',28,'Bold',43],['Heading',23,'Bold',37],['Card title',18,'Bold',29],['Body',16,'Regular',30],['Label',14,'Medium',23],['Small',14,'Regular',25],['Caption',12,'Regular',20]]){const s=figma.createTextStyle();s.name='Concentrate/'+name;s.fontName={family:'Noto Sans JP',style:weight};s.fontSize=size;s.lineHeight={unit:'PIXELS',value:line};styles[name]=s}
function text(parent,value,style='Small',color='ink',width){const n=figma.createText();ids.push(n.id);n.name=value.slice(0,36)||'Text';n.fontName={family:'Noto Sans JP',style:'Regular'};n.characters=value;n.textStyleId=styles[style].id;fill(n,color);parent.appendChild(n);if(width){n.textAutoResize='HEIGHT';n.resize(width,n.height)}return n}
function gap(n,v){n.itemSpacing=v;if(tokens['s'+v])n.setBoundVariable('itemSpacing',tokens['s'+v])}
function pad(n,t,r=t,b=t,l=r){for(const [k,v] of Object.entries({paddingTop:t,paddingRight:r,paddingBottom:b,paddingLeft:l})){n[k]=v;if(tokens['s'+v])n.setBoundVariable(k,tokens['s'+v])}}
function round(n,v){n.cornerRadius=v;if(tokens['r'+v])for(const k of ['topLeftRadius','topRightRadius','bottomLeftRadius','bottomRightRadius'])n.setBoundVariable(k,tokens['r'+v])}
function frame(parent,name,w,dir='VERTICAL',bg=null,spacing=0,padding=0){const n=figma.createAutoLayout(dir);ids.push(n.id);n.name=name;parent.appendChild(n);n.resize(w,1);n.primaryAxisSizingMode=dir==='HORIZONTAL'?'FIXED':'AUTO';n.counterAxisSizingMode=dir==='HORIZONTAL'?'AUTO':'FIXED';fill(n,bg);gap(n,spacing);pad(n,padding);return n}
function border(n){n.strokes=[paint('line')];n.strokeWeight=1}
function icon(parent,name,size=18,color='ink'){const svg=SOURCE.icons[name].replaceAll('currentColor',colors[color]);const n=figma.createNodeFromSvg(svg);n.name='Icon/'+name;parent.appendChild(n);n.resize(size,size);ids.push(n.id,...n.findAll(()=>true).map(x=>x.id));return n}
function component(n,name){const c=figma.createComponentFromNode(n);ids.push(c.id);c.name=name;c.description='Implementation source: app/page.tsx and app/globals.css. Edit shared appearance here; preserve content overrides on instances.';components[name]=c;return c}
function instance(c,parent){const n=c.createInstance();parent.appendChild(n);ids.push(n.id,...n.findAll(()=>true).map(x=>x.id));return n}
function prop(c,n,name){const k=c.addComponentProperty(name,'TEXT',n.characters);n.componentPropertyReferences={characters:k};return k}
function buttonBase(parent,label,variant='Primary',ic){const n=frame(parent,'Button',180,'HORIZONTAL',variant==='Primary'?'green':variant==='Light'?'lime':'white',8);n.counterAxisAlignItems='CENTER';n.counterAxisSizingMode='AUTO';pad(n,10,16);round(n,6);if(variant==='Secondary')border(n);if(ic)icon(n,ic,16,variant==='Primary'?'white':'ink');const tx=text(n,label,'Label',variant==='Primary'?'white':'ink');return {n,tx}}
// Shared assets are kept outside the review frames.
const library=frame(page,'AI Concentrate / Foundations and components',1440,'VERTICAL','surface',24,40);library.x=240;library.y=4000;
text(library,'AI Concentrate / UI foundations','Title');text(library,'実装同期用の共通部品。リデザイン案は別エリアに複製して検討してください。','Small');
const swatches=frame(library,'Colors',1360,'HORIZONTAL',null,12);
for(const k of ['sidebar','green','lime','surface','ink','muted','line']){const s=frame(swatches,k,174,'VERTICAL',null,8);const chip=frame(s,'Color',174,'VERTICAL',k);chip.resize(174,62);chip.primaryAxisSizingMode='FIXED';round(chip,6);text(s,k+'\n'+colors[k],'Caption')}
const buttonRow=frame(library,'Buttons',1360,'HORIZONTAL',null,20);const buttons={};for(const v of ['Primary','Secondary','Light']){const {n,tx}=buttonBase(buttonRow,'ボタン',v);const c=component(n,'Button/'+v);const label=prop(c,tx,'Label');buttons[v]={c,label}}
function button(parent,label,variant='Primary',ic){const b=buttons[variant];const n=instance(b.c,parent);n.setProperties({[b.label]:label});return n}
const navRow=frame(library,'Navigation items',1360,'HORIZONTAL',null,20);const navs={};for(const active of [false,true])for(let j=0;j<4;j++){const n=frame(navRow,'Nav',204,'HORIZONTAL',active?'lime':'sidebar',12);pad(n,12,13);round(n,6);n.counterAxisAlignItems='CENTER';icon(n,['LayoutGrid','FlaskConical','Layers3','BookOpen'][j],18,active?'ink':'darkMuted');const tx=text(n,'企画ライブラリ','Label',active?'ink':'darkMuted');const c=component(n,'Nav/'+j+'/'+(active?'Active':'Default'));navs[String(active)+j]={c,label:prop(c,tx,'Label')}}
const cardBox=frame(library,'Cards and fields',1360,'HORIZONTAL',null,24);
const card=frame(cardBox,'Card',357,'VERTICAL','white',0,21);round(card,8);border(card);const ct=frame(card,'Top',315,'HORIZONTAL',null);ct.primaryAxisAlignItems='SPACE_BETWEEN';const tag=text(ct,'ユースケース','Caption');const num=text(ct,'01','Caption','muted');const title=text(card,'月曜の朝、金曜の自分に聞けたら。','Card title','ink',315);const problem=text(card,'金曜に決めたことと、まだ決めていないことが混ざり、月曜の仕事を始められない。','Small','muted',315);const persona=text(card,'複数の判断を抱える創業者','Caption','muted',315);const foot=frame(card,'Footer',315,'HORIZONTAL',null);foot.primaryAxisAlignItems='SPACE_BETWEEN';const status=text(foot,'原液を編集','Caption','muted');const outputs=text(foot,'2 / 5 媒体','Caption','muted');gap(card,15);const cardComp=component(card,'IdeaCard');const cardProps={};for(const [k,n] of Object.entries({Title:title,Problem:problem,Persona:persona,Axis:tag,Number:num,Status:status,Outputs:outputs}))cardProps[k]=prop(cardComp,n,k);
const fieldFrame=frame(cardBox,'Field',550,'VERTICAL',null,8);const fl=text(fieldFrame,'フィールド名','Label');const input=frame(fieldFrame,'Input',550,'VERTICAL','input',0,12);round(input,5);border(input);const val=text(input,'入力内容','Body','ink',526);const fieldComp=component(fieldFrame,'Field');const fieldProps={label:prop(fieldComp,fl,'Label'),value:prop(fieldComp,val,'Value')};
function field(parent,label,value,w=746,minHeight=0){const n=instance(fieldComp,parent);n.setProperties({[fieldProps.label]:label,[fieldProps.value]:value});n.resize(w,n.height);const box=n.findOne(x=>x.name==='Input');box.resize(w,box.height);const tx=box.findOne(x=>x.type==='TEXT');tx.resize(w-24,tx.height);tx.textAutoResize='HEIGHT';if(minHeight&&box.height<minHeight){box.resize(w,minHeight);box.primaryAxisSizingMode='FIXED'}return n}
function ideaCard(parent,data,index,w=357){const n=instance(cardComp,parent);n.setProperties({[cardProps.Title]:data.title,[cardProps.Problem]:data.problem,[cardProps.Persona]:data.persona,[cardProps.Axis]:data.axis,[cardProps.Number]:String(index+1).padStart(2,'0'),[cardProps.Status]:data.status,[cardProps.Outputs]:Object.values(data.outputs).filter(Boolean).length+' / 5 媒体'});n.resize(w,n.height);for(const tx of n.findAllWithCriteria({types:['TEXT']})){if(['Title','Problem','Persona'].some(k=>tx.componentPropertyReferences?.characters===cardProps[k])){tx.textAutoResize='HEIGHT';tx.resize(w-42,tx.height)}}return n}
const assetRow=frame(library,'Shell components',1360,'HORIZONTAL',null,24);
const side=frame(assetRow,'Sidebar',240,'VERTICAL','sidebar',0);pad(side,30,18);const logo=frame(side,'Logo',204,'HORIZONTAL',null,9);logo.counterAxisAlignItems='CENTER';icon(logo,'FlaskConical',24,'lime');text(logo,'concentrate','Heading','white');text(logo,'AI','Caption','lime');const work=frame(side,'Workspace',204,'HORIZONTAL',null,10,12);work.strokes=[{type:'SOLID',color:rgb('#365044')}];round(work,8);text(work,'将','Heading','lime');const wm=frame(work,'Brand',135,'VERTICAL');text(wm,'ShogunAI','Label','white');text(wm,'Marketing workspace','Caption','darkMuted');gap(side,30);text(side,'WORKSPACE','Caption','darkMuted');const nav=frame(side,'Navigation',204,'VERTICAL',null,5);for(const [j,name] of ['企画ライブラリ','原液エディタ','媒体別ドラフト','ブランドの土台'].entries()){const a=navs[String(j===0)+j];const n=instance(a.c,nav);n.name='Nav item '+j;n.setProperties({[a.label]:name});}
const stretch=frame(side,'Flexible space',204);stretch.resize(204,350);stretch.primaryAxisSizingMode='FIXED';const ph=frame(side,'Phase',204,'VERTICAL','feature',12,15);round(ph,8);text(ph,'01 / 03','Caption','lime');text(ph,'まず、原液を磨こう。','Label','white');text(ph,'企画と編集フローの試作','Caption','darkMuted');text(ph,'次に AI生成、その先に動画制作。','Caption','darkMuted',174);const sidebar=component(side,'Sidebar');
const head=frame(assetRow,'Header',1200,'HORIZONTAL','white',16);pad(head,18,40);head.primaryAxisAlignItems='SPACE_BETWEEN';head.counterAxisAlignItems='CENTER';const crumb=text(head,'ShogunAI　 ›　企画ライブラリ','Caption');const ha=frame(head,'Actions',350,'HORIZONTAL',null,13);ha.counterAxisSizingMode='AUTO';ha.counterAxisAlignItems='CENTER';text(ha,'PROTOTYPE','Caption','muted');icon(ha,'Upload');button(ha,'書き出す','Secondary','Download');const header=component(head,'Header');const crumbProp=prop(header,crumb,'Breadcrumb');
const board=frame(page,'AI Concentrate / Implementation v1',7600,'HORIZONTAL',null,100);board.x=240;board.y=80;
const screens={};function screen(name,key){const root=frame(board,name,1440,'HORIZONTAL','surface',0);root.counterAxisAlignItems='MIN';const si=instance(sidebar,root);si.resize(240,1000);si.primaryAxisSizingMode='FIXED';const main=frame(root,'Main',1200,'VERTICAL','surface');const hi=instance(header,main);hi.setProperties({[crumbProp]:'ShogunAI　 ›　'+name});hi.resize(1200,76);hi.primaryAxisSizingMode='FIXED';const body=frame(main,'Content',1200,'VERTICAL',null,28);pad(body,42,48,60);screens[key]=root.id;return {root,body,si}}
function eyebrow(parent,s,color='muted'){return text(parent,s,'Caption',color)}
function heading(parent,kicker,title,desc,add=false){const row=frame(parent,'Page heading',1104,'HORIZONTAL',null,24);row.primaryAxisAlignItems='SPACE_BETWEEN';row.counterAxisAlignItems='CENTER';const content=frame(row,'Heading',850,'VERTICAL',null,10);eyebrow(content,kicker);text(content,title,'Display','ink',820);if(desc)text(content,desc,'Small','muted');if(add)button(row,'新しい企画','Primary','Plus')}
function note(parent){text(parent,'この試作の編集内容は画面内に保持されます。閉じる・再読み込みの前に「書き出す」で保存し、次回は読み込みボタンから再開できます。','Caption','muted',1104)}
const lib=screen('企画ライブラリ','library');heading(lib.body,'IDEAS BEFORE CONTENT','いいコンテンツは、\nいい原液から。','伝えたいことを磨いて、届け方を広げる。',true);
const feature=frame(lib.body,'Featured concentrate',1104,'HORIZONTAL','feature',30,30);round(feature,10);feature.primaryAxisAlignItems='SPACE_BETWEEN';feature.counterAxisAlignItems='CENTER';const fc=frame(feature,'Featured content',710,'VERTICAL',null,12);eyebrow(fc,'PICK UP / 最初の一本','lime');text(fc,SOURCE.seeds[0].title,'Heading','white');text(fc,'一つの困る瞬間から、原液と媒体別の表現を見てみよう。','Small','darkMuted');button(fc,'原液を編集する','Light','ChevronRight');const flow=frame(feature,'One to many',275,'HORIZONTAL',null,16);flow.counterAxisAlignItems='CENTER';const flask=frame(flow,'Concentrate',105,'VERTICAL','green',10,15);round(flask,8);icon(flask,'FlaskConical',28,'lime');text(flask,'ひとつの原液','Caption','lime');const dest=frame(flow,'Channels',154,'VERTICAL',null,9);for(const [ic,t] of [['Layers3','気づきを届ける'],['FileText','深く伝える'],['Video','場面で見せる']]){const r=frame(dest,t,154,'HORIZONTAL','green',8,8);icon(r,ic,16,'white');text(r,t,'Caption','white');round(r,6)}
const section=frame(lib.body,'Library',1104,'VERTICAL',null,20);const titleRow=frame(section,'Library header',1104,'HORIZONTAL');titleRow.primaryAxisAlignItems='SPACE_BETWEEN';text(titleRow,'企画ライブラリ  5','Card title');text(titleRow,'⌕　企画・ペルソナを検索','Small','muted');const filters=frame(section,'Filters',1104,'HORIZONTAL',null,7);for(const a of ['すべて',...SOURCE.axes])button(filters,a,'Secondary');const grid=frame(section,'Idea grid',1104,'VERTICAL',null,17);for(let r=0;r<2;r++){const row=frame(grid,'Row '+r,1104,'HORIZONTAL',null,17);for(let c=0;c<3;c++){const idx=r*3+c;if(idx<5)ideaCard(row,SOURCE.seeds[idx],idx);else{const newC=frame(row,'New idea',357,'VERTICAL','subtle',15,25);newC.resize(357,288);newC.primaryAxisSizingMode='FIXED';newC.primaryAxisAlignItems='CENTER';newC.counterAxisAlignItems='CENTER';round(newC,8);border(newC);icon(newC,'Plus',24,'muted');text(newC,'次の原液をつくる','Label');text(newC,'まだ、思いつきのままで大丈夫。','Caption','muted')}}}note(lib.body);
function editorTop(body,title){eyebrow(body,'CONCENTRATE / 原液');text(body,title,'Title');const steps=frame(body,'Workflow',1104,'HORIZONTAL',null,20);text(steps,'01　原液を磨く','Label','green');icon(steps,'ChevronRight',16,'muted');text(steps,'02　媒体へ展開する','Label','muted');icon(steps,'ChevronRight',16,'muted');text(steps,'03　制作・公開へ','Caption','muted')}
const data=SOURCE.seeds[0];const ed=screen('原液エディタ','editor');editorTop(ed.body,data.title);const eg=frame(ed.body,'Editor and context',1104,'HORIZONTAL',null,24);const paper=frame(eg,'Concentrate editor',800,'VERTICAL','white',23,27);round(paper,8);border(paper);text(paper,'企画の原液','Card title');field(paper,'企画タイトル',data.title);field(paper,'企画軸 / 編集ステータス',data.axis+'　 /　'+data.status);for(const [k,label,h] of [['persona','誰に届けるか',82],['problem','その人が困る瞬間',110],['claim','一番残したい主張',82],['plot','物語の骨格',170],['body','原液の本文',330]])field(paper,label,data[k],746,h);button(paper,'媒体別ドラフトへ','Primary','ChevronRight');const ctx=frame(eg,'Human and evidence',280,'VERTICAL',null,18);for(const [k,label,eyeb,t] of [['scenes','シーン・演出・体験','HUMAN TOUCH','あなたが足す、具体。'],['evidence','製品情報・検証メモ','SOURCE OF TRUTH','根拠を一緒に持つ。']]){const box=frame(ctx,t,280,'VERTICAL','subtle',15,23);round(box,8);eyebrow(box,eyeb);text(box,t,'Card title');field(box,label,data[k],234,220)}const ai=frame(ctx,'Next stage',280,'VERTICAL','white',15,23);round(ai,8);text(ai,'AI生成は、次のステップ。','Card title','ink',234);text(ai,'今は企画・編集フローの試作です。現在の内容からAIに渡す指示をコピーできます。','Small','muted',234);button(ai,'生成指示をコピー','Secondary');note(ed.body);
const out=screen('媒体別ドラフト','outputs');editorTop(out.body,data.title);const og=frame(out.body,'Channels and draft',1104,'HORIZONTAL',null,24);const cn=frame(og,'Channel navigation',210,'VERTICAL',null,14);text(cn,'届け方を選ぶ','Label');for(const c of SOURCE.channels){const row=frame(cn,c,210,'HORIZONTAL',c==='X'?'subtle':null,10,12);round(row,6);icon(row,c.includes('動画')?'Video':'FileText');text(row,c,'Label')}text(cn,'原液を修正しても、媒体別の編集内容は上書きされません。','Small','muted',190);const op=frame(og,'Draft editor',870,'VERTICAL','white',23,27);round(op,8);border(op);text(op,'X','Card title');text(op,'一つの気づきを、短く。','Small','muted');field(op,'本文・台本',data.outputs.X,816,410);button(op,'この媒体の生成指示をコピー','Secondary','Sparkles');button(op,'本文をコピー','Secondary','Copy');text(op,'試作には事前作成した例が含まれます。ボタンからAI生成は実行されません。','Caption','muted',816);note(out.body);
const br=screen('ブランドの土台','brand');heading(br.body,'BRAND FOUNDATION','すべての企画に、\n同じ土台を。','最初のブランドは、ShogunAI。');const pillars=frame(br.body,'Pillars',1104,'HORIZONTAL',null,20);for(const [i,t,b] of [['01','仕事の記憶','日々の仕事の記録を、必要なときに使える文脈へ。'],['02','文脈の呼び出し','何を決めたかだけでなく、理由と根拠を確認する。'],['03','次の作業の実行','取り戻した文脈を、次の準備や行動につなげる。']]){const p=frame(pillars,t,355,'VERTICAL','subtle',15,28);round(p,8);text(p,i,'Display','muted');text(p,t,'Card title');text(p,b,'Body','muted',299)}const bn=frame(br.body,'Editorial rules',1104,'VERTICAL','white',20,27);round(bn,8);border(bn);text(bn,'編集の共通ルール','Heading');text(bn,'公式サイトの訴求を企画の出発点にします。実装状況・対応連携・効果は、公開前に実機や一次情報で確認します。\n\n・利用者の体験談・発言・成果は、実際に確認できたものを使う。\n・UGC風広告と実際の利用者投稿を区別する。\n・マスコットと城は、記憶・文脈・実行のどれかに結びつける。\n・シーンや独自の見解は、人間が足して磨く。\n\n参照： https://shogunaios.com/ja\n2026年10月2日参照。企画は戦略仮説であり、実証済みの顧客事例ではありません。','Body','ink',1050);note(br.body);
// Mobile library uses the same card and button instances.
const mobile=frame(board,'企画ライブラリ / Mobile 390',390,'VERTICAL','surface',0);screens.mobile=mobile.id;const mobhead=frame(mobile,'Mobile navigation',390,'VERTICAL','sidebar',15,20);text(mobhead,'⚗ concentrate AI','Heading','white');text(mobhead,'企画ライブラリ　原液エディタ　媒体別ドラフト','Caption','lime',350);const mh=frame(mobile,'Header',390,'HORIZONTAL','white',12,20);text(mh,'ShogunAI  ›  企画ライブラリ','Caption');button(mh,'書き出す','Secondary');const mb=frame(mobile,'Content',390,'VERTICAL',null,24,20);eyebrow(mb,'IDEAS BEFORE CONTENT');text(mb,'いいコンテンツは、\nいい原液から。','Title','ink',350);text(mb,'伝えたいことを磨いて、届け方を広げる。','Small','muted',350);button(mb,'新しい企画','Primary','Plus');const mf=frame(mb,'Featured',350,'VERTICAL','feature',14,24);round(mf,10);eyebrow(mf,'PICK UP / 最初の一本','lime');text(mf,data.title,'Heading','white',302);text(mf,'一つの困る瞬間から、原液と媒体別の表現を見てみよう。','Small','darkMuted',302);button(mf,'原液を編集する','Light');text(mb,'企画ライブラリ  5','Card title');for(const [i,d] of SOURCE.seeds.entries())ideaCard(mb,d,i,350);
// Keep source-derived screens and designer exploration clearly separate.
const guide=frame(page,'Designer handoff / Read me',1100,'VERTICAL','white',20,40);guide.x=240;guide.y=-620;text(guide,'AI Concentrate / Designer handoff','Display');text(guide,'01 試作 → 02 AI生成・編集 → 03 動画制作','Heading');text(guide,'このエリアは実装に同期します。デザイナーの探索・リデザインは別のフレームに複製して進めてください。\n実装変更時に既存の同期フレームを更新し、探索案は上書きしません。\n自動双方向同期やバックグラウンド監視は未導入です。\n最終同期：2026-10-02 / 初期プロトタイプ','Body','ink',1020);
const all=board.findAll(()=>true);const types={};for(const n of all)types[n.type]=(types[n.type]||0)+1;
return {createdNodeIds:ids,createdVariableIds:createdVars,collections:[prims.id,sem.id],styles:Object.fromEntries(Object.entries(styles).map(([k,v])=>[k,v.id])),components:Object.fromEntries(Object.entries(components).map(([k,v])=>[k,v.id])),screenIds:screens,boardId:board.id,libraryId:library.id,guideId:guide.id,counts:types,imageNodes:all.filter(n=>'fills'in n&&Array.isArray(n.fills)&&n.fills.some(p=>p.type==='IMAGE')).map(n=>n.id),fonts:[...new Set(all.filter(n=>n.type==='TEXT').map(n=>n.fontName.family))],bounds:Object.fromEntries(Object.entries(screens).map(([k,id])=>{const n=board.children.find(x=>x.id===id);return [k,{x:n.x,y:n.y,width:n.width,height:n.height}]}))};
